### ISSUE TITLE
generalized zero shot learning

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [pujols/zero-shot-learning#1]
Thanks for your nice work!
I am following your wonderful work about zero shot learning, especially generalized zero shot learning. Could you please tell me how to change your code(https://github.com/pujols/zero-shot-learning) to train the the generalized zero shot model and test the generalized zero shot learning accuracy?
Thanks for your help!

**Comment by pujols** [comment]
Hello,

I'm sorry that I missed your issue. Please see our new repo for details. https://github.com/pujols/Zero-shot-learning-journal
